version: '3.8'

services:
    webproxy:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - PORT=3000
        restart: unless-stopped
        volumes:
            - ./public:/usr/src/app/public
            - ./index.mjs:/usr/src/app/index.mjs
        command: ['pnpm', 'start']
